language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
# command to install dependencies
install:
  - "pip install coverage pylint"
  - "pip install -r requirements.txt"
  - "pip install ."
# command to run tests
script:
  - "coverage run runtests.py"
# command to report results
after_script:
  - "coverage report -m"
  - "pylint --py3k hcalendar"
